### PR TITLE
Fix: issue #113 add comments test condition4

### LINKED ISSUE #113: Explain test for condition 4 in comment
Test come from #75

### PR DESCRIPTION
**Pull request by EdwardNorberg**
Add comments to test cases. Condition4 corresponds to LIC 4.

#113

### CODE REVIEW

**Comment by EdwardNorberg** [comment]
Comment for 2nd test is wrong, will need fixing

Edit: should be good now after last commit

**Review by Storsorken — COMMENTED** [review]
For the false-test LIC is accidentally 44 instead of 4. Looks good otherwise

**Comment by EdwardNorberg** [comment]
Think it should be fine now right?

**Review by Storsorken — APPROVED** [review]
LGTM

**Pull request merged**
